<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Beli 1 Gratis 1</name>
   <tag></tag>
   <elementGuidId>7bfb76bf-3bd1-49f9-b518-394b83563571</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='promoMajorBeli1Gratis1Button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#promoMajorBeli1Gratis1Button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b852e331-7612-4810-a392-bf51a14e4864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> button  button--medium button__primary-border--ghost  button__primary-border--ghost-ruparupa</value>
      <webElementGuid>355229aa-b05f-4194-9e66-efc93ed9689e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a0c9262f-6a0a-4b77-8bc1-7016b0402ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>promoMajorBeli1Gratis1Button</value>
      <webElementGuid>21a69361-70e1-416d-b4bd-f2ee06e61221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>promoMajorBeli1Gratis1Button</value>
      <webElementGuid>22cf4de9-ffaf-40ca-91e8-064fd2dc5ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Beli 1 Gratis 1</value>
      <webElementGuid>ea570dfc-83f0-419f-80af-fb49969b2d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;promoMajorBeli1Gratis1Button&quot;)</value>
      <webElementGuid>a899d88d-e937-494f-9f8d-96a535a66d41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='promoMajorBeli1Gratis1Button']</value>
      <webElementGuid>438849f6-bcd9-40e5-b4c8-134b1a2a84bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/section[3]/div/div[2]/div/div/div[3]/div[5]/button</value>
      <webElementGuid>ae8126c8-df5c-40eb-bb35-6db7ba85bc09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selma Promo Baper'])[1]/following::button[1]</value>
      <webElementGuid>ccfb6d15-a963-4b6a-909b-0b74ffce2f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Arrivals'])[1]/following::button[2]</value>
      <webElementGuid>c55c0315-49f2-4a19-a339-5d798e2bea22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk Terlaris'])[1]/preceding::button[1]</value>
      <webElementGuid>6c95c6fb-fda9-4f91-b044-102c1fae4cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Best Rating'])[1]/preceding::button[2]</value>
      <webElementGuid>cd024251-d638-4b79-b446-38355c6441a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Beli 1 Gratis 1']/parent::*</value>
      <webElementGuid>1545300c-11ab-4281-a662-9c44575006fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/button</value>
      <webElementGuid>ffcd902a-b814-463c-b1ea-b552efe6c0a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'promoMajorBeli1Gratis1Button' and @id = 'promoMajorBeli1Gratis1Button' and (text() = 'Beli 1 Gratis 1' or . = 'Beli 1 Gratis 1')]</value>
      <webElementGuid>a0ed90f4-4a9c-4631-a45e-0a043d690a7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
