<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_concat(id(, , close-btn, , ))_close-btn</name>
   <tag></tag>
   <elementGuidId>38ea6ce0-72b7-4d56-adf5-1248c9741245</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='close-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#close-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c4fa5633-5d17-4f95-9fa3-f783b999056b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assets.ruparupa.io/v3/static/homepage/desktop/icon/close-fill.svg</value>
      <webElementGuid>7da3a28c-d313-4e19-a6ef-2735cb137c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close-btn</value>
      <webElementGuid>b396487e-c119-4204-92f0-86e39e873072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>close-btn</value>
      <webElementGuid>2dac5a2a-5d73-4520-97a8-ba5d960ebc04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>close-btn</value>
      <webElementGuid>be995f85-dcae-4e2e-be3b-2e8242eff63d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>9eae2fb5-cb50-4d69-92f4-6dbad0ec61ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>b8bbd3bc-4d0a-459c-8a4b-b4580ae8af39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;close-btn&quot;)</value>
      <webElementGuid>ce2f71de-23b5-4c24-90bf-8d0ea8b519bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='close-btn']</value>
      <webElementGuid>68df5319-7fba-40fa-a3f6-42b3c484346c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='close-btn']</value>
      <webElementGuid>78762844-c06a-4fa2-b7ba-5948847f124a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/img</value>
      <webElementGuid>7f7431c0-ac9e-4f34-b43f-469985f5b3b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://assets.ruparupa.io/v3/static/homepage/desktop/icon/close-fill.svg' and @id = 'close-btn' and @alt = 'close-btn']</value>
      <webElementGuid>130c04d3-0cb8-4926-9bf8-6c3704a4003d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
