<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Last Chance To Buy_homepagePromoBrandPr_379fdb</name>
   <tag></tag>
   <elementGuidId>deb932ad-13e6-479e-98a0-a0b02cbeb6c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='homepagePromoBrandProductImage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#homepagePromoBrandProductImage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3ec6bce0-d207-4db0-a242-66d2211337d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://res.cloudinary.com/ruparupa-com/image/upload/w_200,h_200/f_auto,q_auto/v1537373203/Products/10152183_1.webp</value>
      <webElementGuid>5f32d995-a4c3-4e49-9190-1248daf54edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>susino-payung-lipat-53.5-cm</value>
      <webElementGuid>bcacfb2e-5773-4186-b98e-e98f9beda32a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>homepagePromoBrandProductImage</value>
      <webElementGuid>de354bc2-092c-41b9-861d-35d25a3f0111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>6cde605c-119c-4db6-a30a-9c1eb1a47c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>51c1ed86-ca80-4fcf-a507-9d401ecee1ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;container container__desktop&quot;]/section[@class=&quot;major-promo main-homepage_major-promo__C9atH&quot;]/div[@class=&quot;margin-top-m section-content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;product-promo-section product-row col-xs-8&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-3 product-col&quot;]/div[@class=&quot;row product-card&quot;]/div[@class=&quot;content__product&quot;]/div[@id=&quot;promoMajorCarousel&quot;]/a[@id=&quot;promoMajorProductCard&quot;]/div[@class=&quot;row middle-xs&quot;]/div[@class=&quot;image col-xs-12&quot;]/span[@class=&quot;custom-lazy-load-image  lazy-load-image-background  lazy-load-image-loaded&quot;]/img[@id=&quot;homepagePromoBrandProductImage&quot;]</value>
      <webElementGuid>3c2fa41e-45f5-47d9-b4a4-b3121c919b2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='homepagePromoBrandProductImage']</value>
      <webElementGuid>e718d3fd-54b3-4452-b630-5df9119e8ef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='promoMajorProductCard']/div/div/span/img</value>
      <webElementGuid>708bedd6-1470-40b9-8508-66fb8fe68294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='susino-payung-lipat-53.5-cm']</value>
      <webElementGuid>fd9fa509-6e9e-467b-9145-f3705eca1910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/img</value>
      <webElementGuid>2f33dfec-b573-4d1e-9b2a-bb627e23e948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://res.cloudinary.com/ruparupa-com/image/upload/w_200,h_200/f_auto,q_auto/v1537373203/Products/10152183_1.webp' and @alt = 'susino-payung-lipat-53.5-cm' and @id = 'homepagePromoBrandProductImage']</value>
      <webElementGuid>416d519a-1983-4337-a33a-638911a66417</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
