<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pilih Metode Pembayaran</name>
   <tag></tag>
   <elementGuidId>33fff1ff-16d5-4c48-aa77-1e96abce5bb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.btn-sm.btn-full.font-size-m.bold</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a4e12b52-f12b-4dca-ba24-41f17e647198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9a6cb8e8-b8d6-49de-9997-3d0653d3a600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm btn-full font-size-m bold</value>
      <webElementGuid>9e7b475e-dabf-4d54-92eb-561d52e1484f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Metode Pembayaran</value>
      <webElementGuid>ff3f0a82-2200-4b0c-8be2-16f01770accb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-parent-stick&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-4 no-padding-left&quot;]/div[@class=&quot;pdp-action-right container-card margin-top-s&quot;]/div[@class=&quot;padding-left-s padding-right-s padding-bottom-s&quot;]/button[@class=&quot;btn btn-primary btn-sm btn-full font-size-m bold&quot;]</value>
      <webElementGuid>a2f1c0e1-3153-4add-bba7-b96b0b695ce9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>1fd83a52-a040-4718-a792-ef04453c78bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-parent-stick']/div/div[6]/div/div[2]/button</value>
      <webElementGuid>da04c5aa-125c-406a-a6bd-ade72e6f19cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp88.900'])[1]/following::button[1]</value>
      <webElementGuid>5e8c6d76-7a89-470d-a5dc-2aef8b25209a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grand Total'])[1]/following::button[1]</value>
      <webElementGuid>67d7b4c7-b2fd-467f-90e4-01234456d3fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pilih Metode Pembayaran']/parent::*</value>
      <webElementGuid>0e78359a-c60c-4656-8d9d-ba03282c5f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/button</value>
      <webElementGuid>2ccd9e10-b3c6-4128-9282-439d6ff39d3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Pilih Metode Pembayaran' or . = 'Pilih Metode Pembayaran')]</value>
      <webElementGuid>49d5e87e-66c7-4553-89f6-9279dae3c7bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
