<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tambah Alamat_address_name</name>
   <tag></tag>
   <elementGuidId>e9c051e5-d405-444d-a8cb-cab46d7998f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#address_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e9882eb-15f2-4659-ab4a-c2b9cdd6f903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address_name</value>
      <webElementGuid>e9df5852-80e0-46e9-82f9-09067be5a42c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a1b42489-89bd-42c1-912b-d9e33904c506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input form-control</value>
      <webElementGuid>0317b7f1-ebb0-45a4-b7b7-5fdf325733f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Simpan Alamat Sebagai (Rumah, kantor, kost, dll)</value>
      <webElementGuid>6da7c3a2-e68b-4acb-95c8-8ac36efb128a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>45</value>
      <webElementGuid>fffc7d98-578f-4038-b265-e2f603b68b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address_name&quot;)</value>
      <webElementGuid>5e62a052-2d32-4ec4-8aa6-1450b2bf8b52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address_name']</value>
      <webElementGuid>bb9e5e6b-9cc7-45a1-abdc-840e0b8c3843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AddressNameValidation']/input</value>
      <webElementGuid>5c06effd-a11a-46b3-a8e8-70495d93bee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>d31c2855-36e8-4d4b-9aef-021ac6320c03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'address_name' and @type = 'text' and @placeholder = 'Simpan Alamat Sebagai (Rumah, kantor, kost, dll)']</value>
      <webElementGuid>acb2be3b-6b4c-42b0-a518-b35e71ae997d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
